version: '3.8'

services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_DB: VDT_2025
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5000:5432"
    networks:
      - mynetwork
    volumes:
      - psql-db:/var/lib/postgresql/data

  backend:
    container_name: backend
    build:
      context: ./Backend
    volumes:
      - ./Backend:/usr/src/app/
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    networks:
      - mynetwork

  frontend:
    container_name: frontend-nginx
    build:
      context: ./frontend
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    volumes:
      - ./frontend/ssl:/etc/ssl/private:ro
      - ./nginx/cache:/var/cache/nginx
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  psql-db:
