CREATE TABLE appointments(
  id BIGSERIAL PRIMARY KEY,
  user_id BIGINT CHECK(user_id >0) NOT NULL,
  product_id BIGINT CHECK(product_id >0) NOT NULL,
  date TIMESTAMP NOT NULL,
  amount DECIMAL(18,2) NOT NULL,
  status VARCHAR(50) NOT NULL DEFAULT 'PENDING',
  message VARCHAR DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT fk_product FOREIGN KEY(product_id) REFERENCES products(id) ON DELETE CASCADE,
  CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE

);